<template>
  <div class="main">
    <div class="con-flex">
      <h1 class="tracking-in-contract">
        <span class="a"> Chap<span class="red">ex.ir</span></span>
      </h1>
    </div>

    <div></div>
  </div>
</template>

<script>
export default {};
</script>

<style scoped>
.main {
  background: rgb(242, 242, 242);
  background: linear-gradient(
    20deg,
    rgba(242, 242, 242, 1) 0%,
    rgba(211, 251, 255, 0.5242471988795518) 53%,
    rgba(1, 102, 112, 0.4654236694677871) 100%
  );
}

.con-flex {
  height: 1000px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.tracking-in-contract {
  -webkit-animation: tracking-in-contract 3s cubic-bezier(0.39, 0.575, 0.565, 1)
    infinite both;
  animation: tracking-in-contract 3s cubic-bezier(0.39, 0.575, 0.565, 1)
    infinite both;
}

.a {
  font-size: 50px;
  font-family: Arial, Helvetica, sans-serif;
  font-weight: 900;
  color: #016670;
}
.red {
  color: #930149;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-31 9:59:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-contract {
  0% {
    letter-spacing: 1em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    letter-spacing: normal;
    opacity: 1;
  }
}
@keyframes tracking-in-contract {
  0% {
    letter-spacing: 1em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    letter-spacing: normal;
    opacity: 1;
  }
}
</style>
